name: Publish Docker
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build Image
        run: |
          docker login ghcr.io -u chand1012 --password ${{ secrets.GITHUB_TOKEN }}
          docker build -t summarizer-discord:latest .
          docker tag summarizer-discord:latest ghcr.io/timesurgelabs/summarizer-discord:latest
          docker push ghcr.io/timesurgelabs/summarizer-discord:latest
